### ISSUE TITLE
There was an error while loading all badges! LM-4-1.8.9

### ISSUE THREAD

**Issue by FlynnLG** [cs-jako/LM4-Badges#8]
When starting the latest LabyMod-4-1.8.9 release a error will be displayed and badges etc. will not be displayed on server and also not in the badges overview.

<img width="966" alt="Bildschirmfoto 2023-05-03 um 20 15 27" src="https://user-images.githubusercontent.com/62892734/236007875-50a68e2f-4949-44eb-ad2e-889c1044339e.png">

## Client-Information

Operating System: macOS 12
LabyMod Version: 4.0.0+737 snapshot/f959bc66
Minecraft Version: 1.8.9
Installed Addons: Badges

**Comment by FlynnLG** [comment]
Still persists in LabyMod Version 4.0.0+747 snapshot/dea74f70.

**Comment by cs-jako** [comment]
This is because Minecraft 1.8.9 uses Java 8. The certificate of laby.net (the website where I get the Badge-Data from) is, and I'm not kidding here, too new for Java 8. I might start working on a workaround soon-ish, but I'm currently hoping that either LabyMod itself adds their certificate manually into their client, or they launch Minecraft 1.8.9 with a higher Java-Version.

Speaking of which, using an alternative launcher, such as MultiMC, and selecting a different Java-Version for 1.8.9 will fix the issue.

**Comment by cs-jako** [comment]
While you can change the Java-Version in the official launcher, it will most-likely crash on startup cause it doesn't really like to be started with a different java version.

I personally switched to MultiMC roughly a week ago, changed the Java-Version to 17 and haven't had any issues since then.

**Comment by FlynnLG** [comment]
Tried it with MultiMC and it works. Nevertheless I hope that LabyMod will add their certificate to their client soon. Thanks for your help @cs-jako!

**Comment by cs-jako** [comment]
Fixed in the latest snapshot released today
